### PR TITLE
replace polling with pub sub

### PR DESCRIPTION
**Pull request by perapp**
Due to inconsistent updates using the existing polling mechanism. This PR replaces it with subscribing to Ruuvi tag updates and publishing them to Home Assistant. This works much better for my setup. I think it would be a good improvement in general.

### CODE REVIEW

**Comment by rkallensee** [comment]
I can confirm, this works really good for me, a lot more reliable than the polling mechanism.

**Comment by samuelphy** [comment]
I have also tested this and can confirm that it is performing better than the previous solution.

**Comment by perapp** [comment]
Now also implemented expire time. Old state will expire in 5 min if no new data has arrived. 
Will implement parameter to set expire time next time I find time...

**Comment by sergioisidoro** [comment]
Hi @perapp This is Awesome! 
Thank you so much for your contribution.
I'll check it out on my own setup, and everything is good I'll merge this today :)

**Comment by sergioisidoro** [comment]
This is great. It seems to fix #11 because we're no longer setting the state to `None` if no broadcast arrives during the timeout window, so we can also close #4 

It's also finally using the callbacks after the issue with Linux platform issue in bleson has been fixed, pushed to https://github.com/ruuvi-friends/simple-ruuvitag/pull/4 and now available in `0.0.6`

Indeed it would be great to have an option for the data retention, but I think we can do that after this one is merged. There's also a bit of cleaning up of unused variables and imports, but again, that can be fixed later

I'll let it run for a couple of hours to check the results, but so far everything looks promising. Amazing contribution 💯

**Comment by makuser** [comment]
Are you also experiencing a much higher load with this implementation than with the previous implementation?

**Comment by sergioisidoro** [comment]
@makuser Yes, it was significantly more. But this weekend I created a feature that adds a throttling parameter that defaults to `10` seconds (ie sensor updates max once per 10 secs). Alternatively you can configure the recorder to ease the load. Check: https://github.com/ruuvi-friends/ruuvi-hass.io#throttling-state-updates

**Comment by makuser** [comment]
> @makuser Yes, it was significantly more. But this weekend I created a feature that adds a throttling parameter that defaults to `10` seconds (ie sensor updates max once per 10 secs). Alternatively you can configure the recorder to ease the load. Check: https://github.com/ruuvi-friends/ruuvi-hass.io#throttling-state-updates

Yes I saw that, and since it is the default, it should work without any configuration change. But even after setting it to 30s, the load is still huge.

**Comment by io53** [comment]
Home assistant stores sensor data very inefficient, it's just a string column in the database. I'm using an old laptop (i7-5600U, 12gb ram, ssd) with postgres as HA database and storing sensor data with 30 sec interval, and have purge_keep_days=2. So way faster than rpi4/ha blue standard install, and it's still both a bit sluggish and takes quite a lot of space (granted, I got quite many sensors).
I think the interval should be at least 30s. Maybe even 5+minutes, but then to not loose important updates there could be thresholds. For example update the state immediately if temperature change is greater than 0.5°C since last update.

**Comment by sergioisidoro** [comment]
I had the same experience as @io53 right this weekend. 

I spent hours trying to figure out why was I getting a "lag" in the history graphs. I though it was because this PR introduced some sort of blocking call that was preventing HA from updating the state in the DB (because the state was being updated in the UI correctly), or some bug in home assistant API caching: https://github.com/home-assistant/core/issues/47952

Turns out, it was because the DB was so huge that inserts were taking forever. I took a bit drastic solution of deleting the entire database, and now everything is working fine.

> Maybe even 5+minutes, but then to not loose important updates there could be thresholds. For example update the state immediately if temperature change is greater than 0.5°C since last update.

This is an interesting approach, but we would need to introduce some sort of "update strategy" parameter to the configuration. And allow update by time threshold, or delta threshold (although that's a bit complicated for some entries like movement counters or acceleration).

But having a 5+min interval it's not great for a lot of HA features. For example, I have a configuration that alerts if the temp stays above a threshold for >5min. It would cause jitter on these features.

**Comment by sergioisidoro** [comment]
PS: right now there's a setting that lets you set what parameters from the sensors you want to monitor. 
That will allow you to discard states that you don't actually need:

It needs documentation in the readme tho :/ 

```
sensor:
  - platform: ruuvi
    sensors:
        - mac: 'MA:CA:DD:RE:SS:00'
          name: 'livingroom'
          monitored_conditions:
            -temperature
            -humidity
            -pressure

```

**Pull request merged**
